### ISSUE TITLE
getting empty thumbnail when getting by media url

### ISSUE THREAD

**Issue by wrinkleydog** [raiym/instagram-php-scraper#1]
Whenever I use getMediaByUrl(), the thumbnail is not being returned in the array.  Looks like all the other fields are properly pulled.  Using getMedias on a specific user returns the thumbnail in the array.  

Example: $media = $instagram->getMediaByUrl('https://www.instagram.com/p/BFJUXJ7RdN1/'); will return the array for this post, but thumbnailurl is empty.  

However, $medias = $instagram->getMedias('instaui', 10);  Will return 10 posts, one of which is BFJUXJ7RdN1 (post above) and it contains the proper thumbnailurl.

Thanks!

**Comment by raiym** [comment]
@wrinkleydog yes. Because url contains only one image size -- standard resolution. 

I will take a look for work around.

Thank you

**Comment by raiym** [comment]
@wrinkleydog I have found that you have already resolved it. 
It would be cool if we merge your code!

**Comment by wrinkleydog** [comment]
Sure thing!!

Do you want me to do a pull request?

Great job on this library!  I really like how you approached this.

Chris

**Comment by raiym** [comment]
@wrinkleydog of course. Pull request is cool.

Thank you!

**Comment by raiym** [comment]
I will close after release
