### ISSUE TITLE
Extending getMediasByTag() to support an Offset

### ISSUE THREAD

**Issue by socca1157** [raiym/instagram-php-scraper#11]
Would love to see an Offset value added to getMediasByTag() so we can implement lazy loading to prevent a high initial load. Thought about just loading pieces of the array at a time, but don't want to be constricted by the total max count of the initial array.

`$medias = $instagram->getMediasByTag($hashtag, $quantity,$offset);`

Great work on this!

**Comment by raiym** [comment]
Hello @socca1157  
Today @drthief added paginations in `getMediasByTag()` for now it is the best solution available
