### ISSUE TITLE
Проблемы с выводом параметра isPrivate

### ISSUE THREAD

**Issue by vanGary** [raiym/instagram-php-scraper#18]
При вводе простейшего запроса

use InstagramScraper\Instagram;
$instagram = new Instagram();
$account = $instagram->getAccount('kevin');
echo $account->isPrivate;

не выводится ничего.

Аналогично с параметрами которые должны выводить TRUE/FALSE.

Может я что-то делаю не так?
Должно выводиться в текстовом фомате?

С другими параметрами проблем нет, все описаное работает.

P.S. А также можно улучшить добавив параметр viewer_has_liked может пригодилось бы кому-нибудь, как мне.

**Comment by raiym** [comment]
Попробуйте var_dump($account->isPrivate) выдает значение?

**Comment by vanGary** [comment]
Да, для
**echo var_dump($account->isPrivate);
echo var_dump($account->isVerified);**

выдает значения... **bool(false) bool(false)**
но для
**echo var_dump($medias[0]->captionIsEdited);
echo var_dump($medias[1]->viewerHasLiked);**

выдает **NULL**, а хотелось бы чтобы тоже выдовало. 

Как можно исправить?

**Comment by raiym** [comment]
var_dump($medias[0]->captionIsEdited); - есть не во всех ответах от сервера, например, в этом: https://www.instagram.com/kevin/media/


var_dump($medias[1]->viewerHasLiked); -- вот это поддерживаться не будет, так как юзер должен быть залогинен

**Comment by vanGary** [comment]
Но информация же находится в открытом доступе и не залогинившись видна у любой media.

Например https://www.instagram.com/p/BGuD8sNqUBg/?__a=1
Видна строка "viewer_has_liked". Почему ее не считать оттуда? 
Viewer в данном случае это владелец аккаунта я правильно понимаю?

**Comment by raiym** [comment]
Нет, это тот, кто в данный момент смотрит. В нашем случае php код, который запрашивает страницу. Обратите внимание, что всегда возвращается false

**Comment by vanGary** [comment]
Тогда с этим понятно.
А возможно ли выгрузить последние комменты к определенному media ?
Чтобы возможно было с ними работать, смотреть **от кого('id')** и **что пришло('text')**

**Comment by raiym** [comment]
Можете написать на английском feature request? Думаю, что запрос комментов будет
