### ISSUE TITLE
Get media comments

### ISSUE THREAD

**Issue by raiym** [raiym/instagram-php-scraper#19]

**Comment by vanGary** [comment]
Hi, @raiym !
Everything is good but how its work?

I just type this "

        require "vendor/autoload.php";
        use InstagramScraper\Instagram;
 
        $instagram = new Instagram();

        $comments = Instagram::getMediaCommentsById('1130748710921700586', 10000);

        echo var_dump("Коммент<br> $comments->text");


Result is nothing "
 **string(19) "Коммент
"**
"

Could u please extend your "README" doc for dummies, may be i did something wrong.
