### ISSUE TITLE
Get media by facebookLocationId id

### ISSUE THREAD

**Issue by truth4oll** [raiym/instagram-php-scraper#24]
Library have Endpoint method 'getMediasJsonByLocationIdLink', but it's doesn't used here?

**Comment by raiym** [comment]
@truth4oll, no, but I think it is not hard to include it in next release. 

As I understand it is not foursquare id, it is facebook location id

**Comment by raiym** [comment]
@truth4oll it's done

**Comment by truth4oll** [comment]
Nice! Thank you
