### ISSUE TITLE
A few null entires when using Instagram::getMediasByTag()

### ISSUE THREAD

**Issue by Braveatom** [raiym/instagram-php-scraper#30]
hi there, the results for Instagram::getMediasByTag() is returning a few null entires in the result- 

`$media = Instagram::getMediasByTag('cats', 10);
echo json_encode($media);`

Returns 

`{
id: "1330682029485913958",
createdTime: 1472849681,
type: "image",
link: "https://www.instagram.com/p/BJ3iEFsgPdm",
imageLowResolutionUrl: null,
imageThumbnailUrl: "https://scontent-lhr3-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/14073029_305424399812600_796595869_n.jpg",
imageStandardResolutionUrl: "https://scontent-lhr3-1.cdninstagram.com/t51.2885-15/e35/14073029_305424399812600_796595869_n.jpg",
imageHighResolutionUrl: null,
caption: "Probably the best thing you will see today #books and a #cat #instacat #cats #gamedevcat",
captionIsEdited: null,
isAd: null,
videoLowResolutionUrl: null,
videoStandardResolutionUrl: null,
videoLowBandwidthUrl: null,
videoViews: null,
code: "BJ3iEFsgPdm",
owner: null,
ownerId: "1994837592",
likesCount: 1,
locationId: null,
locationName: null,
commentsCount: 0
},...`

its the username I was after. Weirdly `$account = Instagram::getAccountById(1994837592);
echo $account->username;`

returns a correct name.

**Comment by raiym** [comment]
Hello @Braveatom thank you for issue. 
It is not a bag. 
Username is not presented in response from Instagram (only ownerId), for example: https://www.instagram.com/explore/tags/dubai/?__a=1

In response you can find only owner id, if you want to get username you should query instagram again: 
Instagram::getAccountById(123)
