### ISSUE TITLE
Get more than 20 posts

### ISSUE THREAD

**Issue by eswachsman** [raiym/instagram-php-scraper#34]
`Instagram::getMedias('username')` only returns last 20 posts. Can we get more than that?

**Comment by eswachsman** [comment]
Solved. You need to pass the endCursor variable as the third argument. `Instagram::getMediasByTag('username', 60, 'J0HV-VJTgAAAF0HV-LoYQAAAFiYA');`

You get that back at the first request.

**Comment by raiym** [comment]
Is Instagram::getMedias('username', 60) returning only 20 medias?

**Comment by eswachsman** [comment]
My bad. the page was being cached so I didn't see the new results. After looking into the src code, I see how it works. 

Great project, thanks!
