### ISSUE TITLE
Return Max ID

### ISSUE THREAD

**Issue by fabianoroberto** [raiym/instagram-php-scraper#36]
I need implement a pagination of medias in my application, but your method (getMedias) return only an array of medias.
How i can help you to submit a new PR?

Do you prefer implement another method to return medias and maxId, or passing another params?

**Comment by raiym** [comment]
Hello! 
Not long ago I was in Italy) Really enjoyed it)

Question. Isn't passing `$maxId` in `getMedias($username, $count, $maxId)` not enough in case of pagination?

**Comment by fabianoroberto** [comment]
i'm tried to get last id returned in media element and pass it as max id. Seems not work

**Comment by fabianoroberto** [comment]
A possible solution should be this:

```php
public static function getMediasByTag($tag, $count = 12, $maxId = '', $toObject = false)
    {
        $index = 0;
        $medias = [];
        $hasNextPage = true;
        while ($index < $count && $hasNextPage) {
            $response = Request::get(Endpoints::getMediasJsonByTagLink($tag, $maxId));
            if ($response->code !== 200) {
                throw new InstagramException('Response code is ' . $response->code . '. Body: ' . $response->body . ' Something went wrong. Please report issue.');
            }
            $arr = json_decode($response->raw_body, true);
            if (!is_array($arr)) {
                throw new InstagramException('Response decoding failed. Returned data corrupted or this library outdated. Please report issue');
            }
            if (count($arr['tag']['media']['count']) === 0) {
                return [];
            }
            $nodes = $arr['tag']['media']['nodes'];
            foreach ($nodes as $mediaArray) {
                if ($index === $count) {
                    return $medias;
                }
                $medias[] = Media::fromTagPage($mediaArray);
                $index++;
            }
            if (count($nodes) == 0) {
                return $medias;
            }
            $maxId = $arr['tag']['media']['page_info']['end_cursor'];
            $hasNextPage = $arr['tag']['media']['page_info']['has_next_page'];
        }
        if($toObject === true) {
            $toReturn = [
                'medias'      => $medias,
                'maxId'       => $maxId,
                'hasNextPage' => $hasNextPage
            ];
        } else {
            $toReturn = $medias;
        }
        return $toReturn;
    }
```

**Comment by raiym** [comment]
Let me check it

**Comment by raiym** [comment]
Sorry, you mean `getMediasByTag()` not `getMedias()`? 

If so in getMediasByTag() providing max_id doesn't change anything. Because Instagram using unknown id as `end_cursor`. For example, let's say I want to fetch #dubail hashtag, I go to https://www.instagram.com/explore/tags/dubai/?__a=1

And see JSON, in `[`tag`]['media']['page_info']['end_cursor']` we see `J0HV_yzYgAAAF0HV_yzRgAAAFiYA` but it is not id of media. And I failed to find how this thing is generates. But if you pass it as `$mediaId` as third parameter in `getMediasByTag()` then it will return next page.

**Comment by raiym** [comment]
You meant `getMediasByTag`? Not `getMedias`? 
If so I understand what you mean and feel free to create this pull request I will merge and release update. 
Maybe in future we will find better solution but this is okay. 
Thanks

**Comment by raiym** [comment]
In `getMedias` you can use `$mediaId` as `$maxId` 
But it doesn't work for `getMediasByTag` because as you said they use somehow generated `end_cursor`

**Comment by fabianoroberto** [comment]
I don't know, but sometimes end_cursor == mediaId of last element like here:

https://www.instagram.com/explore/tags/wearepaneedesign/?__a=1
https://www.instagram.com/explore/tags/wearepaneedesign/?__a=1&max_id=959282621811007722.

Anyway, i'll create PR as described above

**Comment by raiym** [comment]
Thanks for contribution. 

I think because the number of medias with this hashtag is low and it fits one request. But if you try to get more `end_cursor` wouldn't be `media_id`. It is my assumption
