### ISSUE TITLE
When i include Endpoints.php

### ISSUE THREAD

**Issue by d3vilsn0w** [raiym/instagram-php-scraper#6]
Parse error: syntax error, unexpected '.', expecting ',' or ';' /scrapper/src/InstagramScraper/Endpoints.php on line 8

**Comment by raiym** [comment]
@d3vilsn0w please update to v0.2.1 and check

**Comment by socca1157** [comment]
Just downloaded latest version and getting same error.

**Comment by raiym** [comment]
What version of PHP are you using? @d3vilsn0w

**Comment by raiym** [comment]
I will update library to support older than 5.6 versions

**Comment by d3vilsn0w** [comment]
PHP Version 5.5.36, Can you please update it now, As i really need to get it working asap. Thanks a lot. @raiym

**Comment by raiym** [comment]
yes

**Comment by d3vilsn0w** [comment]
Thank you, I'm waiting.

**Comment by raiym** [comment]
It is done. please check

**Comment by d3vilsn0w** [comment]
That was fast. I can confirm it is working fine now. Thanks again.

**Comment by raiym** [comment]
Cool

**Comment by socca1157** [comment]
Thank you!
