### ISSUE TITLE
Ошибка при использовании библиотеки

### ISSUE THREAD

**Issue by djken84** [raiym/instagram-php-scraper#7]
Привет.
Впервые использую autoload и composer, но думаю сделал все правильно.
Через терминал composer require raiym/instagram-php-scraper потянул мне в проект Mashape Unirest и Instagram Scraper.
![2016-06-06 15 36 52](https://cloud.githubusercontent.com/assets/19777449/15822205/024417f0-2bfd-11e6-9195-15d07726654b.png)

В файле test.php пишу:
```
<?php

require_once 'vendor/autoload.php';

use InstagramScraper\Instagram;

$instagram = new Instagram();
$account = $instagram->getAccount('denis_ken');
echo $account->fullName;
```

Запускаю скрипт: сайт не может обработать запрос, HTTP ERROR 500

Покопался в методе getAccount класса Instagram. Массив приходит в $userArray. Ошибка возникает при вызове `return Account::fromAccountPage($userArray['user']);`
Копался дальше - понял, что не видит класс Account. Что я делаю не так? Или изначально не правильно установил?..

Заранее спасибо за помощь.

**Comment by raiym** [comment]
Привет, действительно баг. Сейчас поправлю и выкачу обновление

**Comment by raiym** [comment]
@djken84 проверьте пожалуйста

**Comment by djken84** [comment]
Отлично! Все работает )
Большое спасибо )

**Comment by raiym** [comment]
Спасибо за репорт
