### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by socca1157** [raiym/instagram-php-scraper#8]
When I use `$medias = $instagram->getMediasByTag('flume', 60);`

It is only returning 13-17 images depending on the hashtag. Not even 20, and definitely not 60.

How can I go about getting 60 or so images via a hashtag?

Thanks for all your efforts so far.

**Comment by raiym** [comment]
Yeah, I have already seen it. 
I use max_id parameter to paginate through medias. Some times it works and some times doesn't, it is up to Instagram. 
I will look into it to find more stable method. 
thank you

**Comment by raiym** [comment]
Well. I was so inattentive and missed it. 

Gut from Russian blog really helped (https://habrahabr.ru/post/302150/#comment_9645946). Special thanks

So I released new version, please check

**Comment by socca1157** [comment]
🙌 🙌 🙌 Working well! Fantastic work @raiym @350d. Does the getMediasByTag() method support an offset in case we want to do lazy loading?

**Comment by raiym** [comment]
@socca1157 please submit new issue. It seems possible

**Comment by maliayas** [comment]
Hi. How can we specify max id in `::getMediasByTag($tag, $limit, $maxId)`? It seems only that method knows it. I try to use last media ID but then it gives empty response.

**Comment by raiym** [comment]
@maliayas 
Please see issue #11 

You cannot specify media_id as max_id in tag feed (but it works with account media feed).
Work around: you can use (and save) end_cursor and start_cursor (from response) for pagination purpose
