### ISSUE TITLE
How to install this script to my server?

### ISSUE THREAD

**Issue by galuh33** [raiym/instagram-php-scraper#9]

**Comment by raiym** [comment]
It seems there are two way to use this library in your project.
Through composer or through direct download (git clone). 

Please specify your question

**Comment by galuh33** [comment]
can i install this script on cpanel ?

**Comment by raiym** [comment]
Don't no yet

**Comment by galuh33** [comment]
done. thank you.

**Comment by maxhuro** [comment]
Hello @galuh33 how did you install on the server?
